DROP TABLE IF EXISTS RetailSales;  
CREATE TABLE RetailSales (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
dealer_code VARCHAR(50) NOT NULL,
month INT(8) NOT NULL,
year INT(8) NOT NULL,
qty INT(8) NOT NULL
);

DROP TABLE IF EXISTS DailySalesRate;  
CREATE TABLE DailySalesRate (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
dealer_code VARCHAR(50) NOT NULL,
month INT(8) NOT NULL,
year INT(8) NOT NULL,
qty INT(8) NOT NULL
);

DROP TABLE IF EXISTS CarlineSales;  
CREATE TABLE CarlineSales (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
carline VARCHAR(50) NOT NULL,
status VARCHAR(50),
month INT(8) NOT NULL,
year INT(8) NOT NULL,
qty INT(8) NOT NULL
);

DROP TABLE IF EXISTS ROCounts;  
CREATE TABLE ROCounts (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
RO_DLR_CD VARCHAR(50) NOT NULL,
RO_COMPLETE_DATE VARCHAR(50),
TOTAL_CAR_COUNT INT(8) NOT NULL,
TOTAL_RO_COUNT INT(8) NOT NULL,
WARRANTY_RO_COUNT INT(8) NOT NULL,
CUST_PAY_RO_COUNT INT(8) NOT NULL,
INTERNAL_RO_COUNT INT(8) NOT NULL,
LAST_UPDT_DT VARCHAR(50)
);

DROP TABLE IF EXISTS PartsAccessoriesSalesTotalParts;  
CREATE TABLE PartsAccessoriesSalesTotalParts (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
DLR_CD VARCHAR(50) NOT NULL,
PART_SALE_DATE VARCHAR(50),
PART_CATEGORY VARCHAR(50),
TOTAL_PARTS_SALES DECIMAL(8,2) NOT NULL,
DAILY_OBJECTIVES VARCHAR(50),
W_UPDT_DT VARCHAR(50)
);
